### PR TITLE
Adds a language switcher in the header

### PR DESCRIPTION
**Pull request by AnderzL7**
image
image
image

### CODE REVIEW

**Comment by AnderzL7** [comment]
After a discussion with Daniel I added a dropdown arrow to make the functionality more obvios 25cafdc
image

**Comment by AnderzL7** [comment]
Right aligned dropdown after consultation with UI/UX designer 53856ef
image

**Comment by DanielNeset** [comment]
lgtm

**Review by DanielNeset — APPROVED** [review]
lgtm

**Pull request merged**
